# Minimal configuration

[[server]]
name = "S1"
port = 3336

[[target]]
name = "SP1"
url = "stratum+tcp://radioactive.sytes.net:1027"
user_identity = "userName.workerName"

[[target]]
name = "SP2"
url = "stratum+tcp://radioactive.sytes.net:1029"
user_identity = "userName.workerName"

[[target]]
name = "SP3"
url = "stratum+tcp://radioactive.sytes.net:1030"
user_identity = "userName.workerName"

[[routing]]
from = ["S1"]

[[routing.goal]]
name = "Primary Goal"

[[routing.goal.level]]
targets = ["SP1", "SP2", "SP3"]
