# Sample configuration

[[server]]
name = "S1"
# Port to listen on
port = 3336
# Bonus related to devfee
#slushpool_bos_bonus = "bosBonusUserName"

[[target]]
# Name of this target
name = "SP1"
# Pool URL
url = "stratum+tcp://radioactive.sytes.net:1027"
# Mining identity that FP should perform initial authorization with.
# Format: `<tag>[.<worker_name>]`
user_identity = "userName.workerName"
# Maximum number of mining session aggregated per connection
#aggregation = 50

[[target]]
# Name of this target
name = "SP2"
# Pool URL
url = "stratum+tcp://radioactive.sytes.net:1029"
# Mining identity that FP should perform initial authorization with.
# Format: `<tag>[.<worker_name>]`
user_identity = "userName.workerName"
# Maximum number of mining session aggregated per connection
#aggregation = 50

[[target]]
# Name of this target
name = "SP3"
# Pool URL
url = "stratum+tcp://radioactive.sytes.net:1030"
# Mining identity that FP should perform initial authorization with.
# Format: `<tag>[.<worker_name>]`
user_identity = "userName.workerName"
# Maximum number of mining session aggregated per connection
#aggregation = 50

[[routing]]
# Routing Domain name
name = "RD"
# List of servers that will be exclusive used within this Routing Domain
from = ["S1"]

[[routing.goal]]
# Name of this goal
name = "Primary Goal"
# Weight of this goal
#hr_weight = 100

[[routing.goal.level]]
# Targets that HR will be sent to for this Goal
targets = ["SP1", "SP2", "SP3"]
