# Full server configuration
[[server]]
name = "S1"
port = 3336

# Minimal server configuration
[[server]]
name = "S2"
port = 3337

# Full target configuration
[[target]]
name = "SP1"
url = "stratum+tcp://radioactive.sytes.net:1027"
user_identity = "userName.workerName"

[[target]]
name = "SP2"
url = "stratum+tcp://radioactive.sytes.net:1029"
user_identity = "userName.workerName"

[[target]]
name = "SP3"
url = "stratum+tcp://radioactive.sytes.net:1030"
user_identity = "userName.workerName"

[[routing]]
from = ["S1", "S2"]

[[routing.goal]]
hr_weight = 100
name = "Goal 100%"

[[routing.goal.level]]
targets = ["SP1", "SP2", "SP3"]
